name: bio_batch_BO_3
channels:
  - defaults
dependencies:
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.5
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - matplotlib-inline=0.1.6
  - pip=24.2
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - yaml=0.2.5
  - pip:
    - anndata==0.10.9
    - array-api-compat==1.9.1
    - contourpy==1.3.1
    - cycler==0.12.1
    - filelock==3.16.1
    - fonttools==4.55.2
    - fsspec==2024.10.0
    - gpytorch==1.13
    - h5py==3.12.1
    - jaxtyping==0.2.19
    - joblib==1.4.2
    - kiwisolver==1.4.7
    - linear-operator==0.5.3
    - matplotlib==3.9.2
    - mpmath==1.3.0
    - natsort==8.4.0
    - networkx==3.4.2
    - numpy==1.26.4
    - pandas==2.2.3
    - pillow==11.0.0
    - pyparsing==3.2.0
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sympy==1.13.3
    - threadpoolctl==3.5.0
    - torch==2.2.2
    - typeguard==4.4.1
    - tzdata==2024.2
